// Generated by packages/shared/scripts/emoji-metrics.ts from Core Text on macOS.
// Do not edit by hand: re-run the script when Apple Color Emoji changes.

/** Apple Color Emoji as Core Text sets it in a caption run, in em of the run's font size. */
export const APPLE_COLOR_EMOJI = {
  /** The font's version string when this was generated. */
  version: "22.0d3e2",
  /** Advance of one emoji cluster (🔥 👍🏽 🇺🇸 👨‍👩‍👧 #️⃣ ❤️ ❤‍🔥 ☝🏽 all measured alike). */
  advanceEm: 1,
  ascentEm: 1,
  descentEm: 0.3125,
} as const;
