/*
 * Generates packages/shared/src/caption-emoji-metrics.ts by asking Core Text
 * (macOS only) how Apple Color Emoji sets emoji: the advance of one emoji
 * cluster in a run of the bundled caption face, and the emoji font's ascent
 * and descent, all in em, plus the font's version string so a drift is
 * visible in review (plan decision OV7).
 *
 *   npx tsx packages/shared/scripts/emoji-metrics.ts          # rewrite the module
 *   npx tsx packages/shared/scripts/emoji-metrics.ts --check  # fail if it is stale
 *
 * Run it on macOS with Xcode's `swift`. The macOS CI engine job can run
 * --check; the OV7 corpus test should also run on the iOS 26 simulator once
 * that job has one, since iOS ships its own copy of the font.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const FONT_PATH = resolve(here, '../../../server/fonts/Montserrat-Bold.ttf');
export const EMOJI_OUTPUT_PATH = resolve(here, '../src/caption-emoji-metrics.ts');

/** Clusters measured: plain, skin tone, flag, ZWJ family, keycap, VS16 heart, ZWJ heart on fire. */
const SAMPLES = ['🔥', '👍🏽', '🇺🇸', '👨‍👩‍👧', '#️⃣', '❤️', '❤‍🔥', '☝🏽'];

const SWIFT = `
import CoreText
import Foundation
let size: CGFloat = 1000
let url = URL(fileURLWithPath: CommandLine.arguments[1]) as CFURL
let face = CTFontCreateWithFontDescriptor((CTFontManagerCreateFontDescriptorsFromURL(url) as! [CTFontDescriptor])[0], size, nil)
let emoji = CTFontCreateWithName("AppleColorEmoji" as CFString, size, nil)
func width(_ text: String) -> Double {
  let attributes: [NSAttributedString.Key: Any] = [
    NSAttributedString.Key(kCTFontAttributeName as String): face,
    NSAttributedString.Key(kCTLigatureAttributeName as String): 0,
  ]
  return CTLineGetTypographicBounds(CTLineCreateWithAttributedString(NSAttributedString(string: text, attributes: attributes)), nil, nil, nil)
}
var out: [String: Any] = [
  "version": (CTFontCopyName(emoji, kCTFontVersionNameKey) as String?) ?? "unknown",
  "ascent": CTFontGetAscent(emoji) / size,
  "descent": CTFontGetDescent(emoji) / size,
]
var samples: [String: Double] = [:]
for sample in CommandLine.arguments.dropFirst(2) { samples[sample] = width(sample) / size }
out["samples"] = samples
print(String(data: try! JSONSerialization.data(withJSONObject: out, options: [.sortedKeys]), encoding: .utf8)!)
`;

export interface EmojiMeasurement { version: string; ascent: number; descent: number; samples: Record<string, number> }

/** Runs the Core Text measurement (macOS with Swift only). */
export function measureEmojiMetrics(): EmojiMeasurement {
  const directory = mkdtempSync(join(tmpdir(), 'emoji-metrics-'));
  try {
    const script = join(directory, 'measure.swift');
    writeFileSync(script, SWIFT);
    return JSON.parse(execFileSync('swift', [script, FONT_PATH, ...SAMPLES], { encoding: 'utf8' })) as EmojiMeasurement;
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

const round = (value: number): number => Math.round(value * 1e4) / 1e4;

export function buildEmojiModule(measured: EmojiMeasurement): string {
  const advances = [...new Set(SAMPLES.map((sample) => round(measured.samples[sample] ?? Number.NaN)))];
  if (advances.length !== 1 || !Number.isFinite(advances[0])) {
    throw new Error(`emoji clusters do not share one advance: ${JSON.stringify(measured.samples)}`);
  }
  return [
    '// Generated by packages/shared/scripts/emoji-metrics.ts from Core Text on macOS.',
    '// Do not edit by hand: re-run the script when Apple Color Emoji changes.',
    '',
    '/** Apple Color Emoji as Core Text sets it in a caption run, in em of the run\'s font size. */',
    'export const APPLE_COLOR_EMOJI = {',
    `  /** The font's version string when this was generated. */`,
    `  version: ${JSON.stringify(measured.version)},`,
    `  /** Advance of one emoji cluster (${SAMPLES.join(' ')} all measured alike). */`,
    `  advanceEm: ${advances[0]},`,
    `  ascentEm: ${round(measured.ascent)},`,
    `  descentEm: ${round(measured.descent)},`,
    '} as const;',
    '',
  ].join('\n');
}

function main(): void {
  const text = buildEmojiModule(measureEmojiMetrics());
  if (process.argv.includes('--check')) {
    if (readFileSync(EMOJI_OUTPUT_PATH, 'utf8') !== text) {
      console.error(`${EMOJI_OUTPUT_PATH} is stale: run npx tsx packages/shared/scripts/emoji-metrics.ts on macOS`);
      process.exit(1);
    }
    return;
  }
  writeFileSync(EMOJI_OUTPUT_PATH, text);
  console.log('wrote packages/shared/src/caption-emoji-metrics.ts');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
